version: 2

build:
  image: testing
  os: ubuntu-22.04

sphinx:
  configuration: source/conf.py

python:
  version: '3.9'
  install:
    - method: pip
      path: source/
    - requirements: source/requirements.txt
